background_color: '#454545'
font_color: '#ffffff'
displays:
  CPU:
    color: '#77767b'
    enabled: true
    temp: true
    util: true
  GPU:
    color: '#77767b'
    enabled: true
    temp: true
    util: true
  RAM:
    color: '#77767b'
    enabled: true
    usage: true
    util: true
ip: "0.0.0.0"
port: "0000"
update_rate: 1
gpu_vendor: "None"
cpu_vendor: "None"
