background_color: '#454545'
displays:
  CPU:
    color: '#77767b'
    enabled: true
    temp: true
    util: true
  GPU:
    color: '#77767b'
    enabled: true
    temp: true
    util: true
ip: "0.0.0.0"